# Array

In [1]:
import numpy as np
x=[1,2,3,4]
y = np.array(x)
print(y)


[1 2 3 4]


In [4]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
l = []
for i in range(1,5):
    int_1 = int(input("enter the value: "))
    l.append(int_1)
    
print(np.array(l))

enter the value: 8
enter the value: 9
enter the value: 99
enter the value: 89
[ 8  9 99 89]


In [10]:
ar2 = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
2


In [11]:
ar3 = np.array([[[1,2,3],[1,2,3]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 2 3]]]
3


In [12]:
arn = np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
