In [1]:
import numpy as np
import pandas as pd

In [3]:
dataset=pd.read_csv('data.csv')

In [4]:
dataset

Country  Age Salary Purchased
0   France   44  72000        No
1    Spain   27  48000       Yes
2  Germany   30  54000        No
3    Spain   38  61000        No
4  Germany   40    Nan       Yes
5   France   35  58000       Yes
6    Spain  Nan  52000        No
7   France   48  79000       Yes
8  Germany   50  83000        No
9   France   37  67000       Yes

In [6]:
x=dataset[['Country','Age','Salary']].values
x

array([['France', '44', '72000'],
       ['Spain', '27', '48000'],
       ['Germany', '30', '54000'],
       ['Spain', '38', '61000'],
       ['Germany', '40', 'Nan'],
       ['France', '35', '58000'],
       ['Spain', 'Nan', '52000'],
       ['France', '48', '79000'],
       ['Germany', '50', '83000'],
       ['France', '37', '67000']], dtype=object)

In [7]:
y=dataset[['Purchased']].values
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [8]:
from sklearn.impute import SimpleImputer

In [9]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')


In [10]:
imputer=imputer.fit(x[:,1:3])

In [11]:
x

array([['France', '44', '72000'],
       ['Spain', '27', '48000'],
       ['Germany', '30', '54000'],
       ['Spain', '38', '61000'],
       ['Germany', '40', 'Nan'],
       ['France', '35', '58000'],
       ['Spain', 'Nan', '52000'],
       ['France', '48', '79000'],
       ['Germany', '50', '83000'],
       ['France', '37', '67000']], dtype=object)

In [12]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [13]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
from sklearn.preprocessing import LabelEncoder

In [16]:
label_encoder_x=LabelEncoder()

In [17]:
x[:,0]=label_encoder_x.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
onehotencoder=OneHotEncoder()

In [20]:
x=onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [21]:
labelencoder_y=LabelEncoder()

In [22]:
y=labelencoder_y.fit_transform(y)

C:\Users\preet\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [26]:
y_test

array([0, 0])

In [27]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)

In [28]:
x_test=sc_x.transform(x_test)

In [29]:
x_train
x_test

array([[-1.        ,  2.64575131, -0.77459667],
       [-1.        ,  2.64575131, -0.77459667]])

In [30]:
x_train


array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [31]:
x_test

array([[-1.        ,  2.64575131, -0.77459667],
       [-1.        ,  2.64575131, -0.77459667]])