# NumPy Functions

In [1]:
import numpy as np

# arange()

In [2]:
#np.arange(start, end, steps)
ar_1d = np.arange(1,11)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
even_ar = np.arange(2,11,2)
print(even_ar)

[ 2  4  6  8 10]


# linspace()

In [4]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape

In [5]:
ar_2d = ar_1d.reshape(2,5)
print(ar_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
ar_3d = ar_1d.reshape(1,2,5)
print(ar_3d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


In [7]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel 

In [8]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [9]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose() 

In [10]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [11]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])