In [1]:
import numpy as np

In [2]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])

In [3]:
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
mx_1s = np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [5]:
mx_1s.dtype

dtype('float64')

In [6]:
mx_1s = np.ones((3,4), dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
mx_1s.dtype

dtype('int32')

In [8]:
mx_0s = np.zeros((4,6), dtype = bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]
